name: hampprocenv
channels:
  - defaults
  - conda-forge
dependencies:
  - bzip2=>1.0.8
  - ca-certificates=>2024.7.4
  - libexpat=>2.6.2
  - libffi=>3.4.2
  - libsqlite=>3.46.0
  - libzlib=>1.3.1
  - ncurses=>6.5
  - openssl=>3.3.1
  - pip=>24.2
  - python=>3.12.5
  - readline=>8.2
  - setuptools=>72.1.0
  - tk=>8.6.13
  - tzdata=>2024a
  - wheel=>0.44.0
  - xz=>5.2.6
  - pip:
    - numpy
    - pandas
    - scipy
    - matplotlib
    - xarray
    - netcdf4

# PLEASE NOTE:
#   you also need to install the pyorcestra package,
#   e.g. navigate to your pyorcestra directory and execute `python -m pip install -e .`
