root: /Users/jakobdeutloff/Programming/Orcestra/hamp_processing/Data
radar: /Radar_Data/HALO-{date}a/*.nc
radiometer: /Radiometer_Data/HALO-{date}a
bahamas: "/Bahamas_Data/HALO-{date}a/QL_HALO-{date}a_BAHAMAS_V01.nc"
sea_land_mask: /Aux/sea_land_mask.nc
save_dir: /Hamp_Processed
