name: CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v4
      - uses: conda-incubator/setup-miniconda@v3
        with:
          activate-environment: hampprocenv
          environment-file: environment.yaml
          auto-activate-base: false

      - name: Conda Info
        run: |
          conda info
          conda list

      - name: Activate Conda Environment
        run: |
          conda init
          source /home/runner/.bashrc
          conda activate /usr/share/miniconda/envs/hampprocenv
          conda info --envs
